### ISSUE TITLE
Event new scopes

### ISSUE THREAD

**Issue by nafiislam** [nafiislam/OnCampusFrontEnd#4]
fixed:
Rag concert->
Bands : 1.Internal Bands
        2.HeadLiners
Restrictions:
	1.
	2.

Workshop->links and files
Seminar-> links and files

others:
Flash mob
Competitions
Club events
Festivals
Shapa day

locations:
IAC
ECE cafe
BUET Auditorium
BUET cafeteria
BUET Central Field
Main campus
ECE Building

types:
General
Batch
Dept
BatchDept

two types of saving:
participating
saved //

timeline adding

clubs? ->clubname select

**Comment by Nahin009** [comment]
single event (any student can create)

pre-defined event types - workshop, seminars, competitions, sports, festivals, shapa-day, flashmobs, rag-concert...


Default	
	 
	mandatory -
	 - title
	 - start time
	 - location
	 - general description
	 - hosting (can be club or batch or batch-dept)
	 
	 	competitions
		 - registration
		 - prizepool


		rag concert
		 - bands
		 
		workshop & seminar
		 - online link
		 - registration
		 - resources

		 
	Optional
	 - end time
	 - sponsors
	 - rules
	 
	 
Also, event creator will have options for including additional field... But the field should must have title and description
		 
		 
		 
event groups

 mandatory - name, description,  start date, ending status(ended or not)
 
later when a person creates any event, he/she will have a option to add that event to an running or upcoming event group



location confliction warning
	-IAC
	-ECE cafe
	-BUET Auditorium
	-BUET cafeteria
	-BUET Central Field
	-Main campus
	-ECE Building

**Comment by Nahin009** [comment]
event -> 
my events
create event
create event group
geAllEvents
getEvent/:id

**Comment by Nahin009** [comment]
workshop/seminar timeline(both for online and offline)
1st person speech, 2nd person speech, lunch break, short xm etc...

**Comment by Nahin009** [comment]
Cultural, tour, Picnic etc. are same type

Cultural and picnic are one day, so timeline will contain just time

but tour is multi day, so timeline will contain both date and time

**Comment by Nahin009** [comment]
[aa.zip](https://github.com/nafiislam/OnCampusFrontEnd/files/14229962/aa.zip)
